traffic_class_mappings:
  - 0:
      src_addr: "1.1.1.1"
      src_port: 1
      dest_addr: "2.2.2.2"
      dest_port: 1
      protocol: 0
  - 1:
      src_addr: "1.1.1.1"
      src_port: 35
      dest_addr: "2.2.2.2"
      dest_port: 35
      protocol: 1
traffic_class_policies:
  0: "OPTIMIZE_DELAY"
  1: "OPTIMIZE_LOSS"
tunnel_headers:
  0:
    version: 0
    traffic_class: 0
    flow_label: 0
    payload_len: 0
    next_header: 0
    hop_limit: 0
    src_addr: 1111111
    dest_addr: 2222222
  1:
    version: 0
    traffic_class: 0
    flow_label: 0
    payload_len: 0
    next_header: 0
    hop_limit: 0
    src_addr: 3333333
    dest_addr: 4444444
